config/routes.rb
Rails.application.routes.draw do
  #DB確認用
  get "users" => "users#index"
  get "contents" => "contents#index"
  get "favorites" => "favorites#index"
  #音楽登録API
  post "resister" => "contents#resister"
  #お気に入り登録
  post "fav/add" => "favorites#add"
  #ユーザの登録
  post "user/add" => "users#add"
  #ログイン用
  get "auth" => "users#auth"
  #写真のコンテンツ用
  get "image/:id" => "contents#image"
  #音楽のコンテンツ用
  get "sound/:id" => "contents#sound"
  #自分が投稿した音楽
  get "post" => "users#home"
  get "home" => "contents#home"
  #タイトル検索
  get "search" => "contents#search"
  #直近のN件を取得
  get "current" => "contents#current"
  #閲覧する際のデータ取得
  get "show" => "contents#watch"
  #お気に入り呼び出し
  get "fav/search" => "favorites#search"
  get "fav/show" => "contents#fav"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  def index
    @contents = Content.all.select("id, title")
    render :json => @contents
  end

  def image
    @content = Content.find(params[:id])
    send_data @content.image, filename: @content.title, :type => 'image/jpeg', :disposition => 'inline'
  end

  def sound
    @content = Content.find(params[:id])
    send_data @content.sound, filename: @content.title, :type => 'audio/mp3', :disposition => 'inline'    
  end

  def current
    @num = params[:num].to_i
    @contents = Content.limit(@num).order(created_at: "DESC").select("id, title")
    render :json => @contents
  end

  def resister
    @image = params[:image]
    @sound = params[:sound]
    data = {
      "user_id":params[:user_id],
      "title":params[:title],
      "image":@image.read,
      "sound":@sound.read
    }
    @content = Content.new(data)
    if @content.save
      result = {"status": "success", "id": @content.id}
    else
      result = {"status": "failed"}
    end
    render :json => result
  end

  def fav
    contents = []
    @count = params[:data]
    @count.each do |c|
      @content = Content.find(c.to_i).select("id, title")
      contents.append(@content)
    end
    render :json => contents
  end

  def search
    t = "%" + params[:title] + "%"
    @contents = Content.where("title LIKE ?", t).select("id, title")
    render :json => @contents
  end

  def watch
    @content = Content.where(id: params[:id]).select("id, title")
    @contents = Content.order("RANDOM()").limit(10).select("id, title")
    data = {"main": @content, "other": @contents}
    render :json => data
  end

  def home
    @contents = Content.where(user_id: params[:id]).select("id, title")
    render :json => @contents
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  def index
    @favorites = Favorite.all.select("id, user_id, content_id")
    render :json => @favorites
  end

  def add
    data = {
      "user_id":params[:user_id],
      "content_id":params[:content_id]
    }
    @favorite = Favorite.new(data)
    if @favorite.save
      result = {"status": "success"}
    else
      result = {"status": "failed"}
    end
    render :json => result
  end

  def search
    @favorites = Favorite.where(user_id: params[:user_id])
    data = []
    @favorites.each do |f|
      if f.content_id.nil? == false
        data.append(f.content_id)
      end
    end
    redirect_to controller: 'contents', action: 'fav', data: data
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.select("id, username")
    render :json => @users
  end

  def auth
    @user = User.find_by(username: params[:username], password: params[:password])
    if @user.nil?
      data = {"status": "false"}
    else
      data = {"status": "true", "id": @user.id}
    end
    render :json => data
  end

  def add
    data = {
      "username":params[:username],
      "password":params[:password]
    }
    @user = User.new(data)
    if @user.save
      result = {"status": "success", "id": @user.id}
    else
      result = {"status": "failed"}
    end
    render :json => result
  end

  def home
    @user = User.find_by(username: params[:username])
    redirect_to controller: 'contents', action: 'home', id: @user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
        <% content.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :sound %>
    <%= form.text_field :sound %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contents</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Image</th>
      <th>Sound</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.user_id %></td>
        <td><%= content.title %></td>
        <td><%= content.image %></td>
        <td><%= content.sound %></td>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @content.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @content.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @content.image %>
</p>

<p>
  <strong>Sound:</strong>
  <%= @content.sound %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/favorites/_form.html.erb
<%= form_with(model: favorite, local: true) do |form| %>
  <% if favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
        <% favorite.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :content_id %>
    <%= form.number_field :content_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favorites</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user_id %></td>
        <td><%= favorite.content_id %></td>
        <td><%= link_to 'Show', favorite %></td>
        <td><%= link_to 'Edit', edit_favorite_path(favorite) %></td>
        <td><%= link_to 'Destroy', favorite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite', new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favorite.user_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @favorite.content_id %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sounds</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>